version: '3.4'

services:

  webapp:
    image: webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      DB_HOST: dbpostgres
      DB_PORT: 5432
      DB_NAME: userssm
      DB_USER: user
      DB_PASSWORD: password
    networks:
      - default

  dbpostgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d

#  dbmongo:
#    image: mongo
#    restart: always
#    ports:
#      - 27017:27017
#    networks:
#      - default
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
#    volumes:
#      - mongodb-data:/data/db/

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - default

# ---------------------------------------------------
# Interfaces para las BD 

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: UserTest@Gmail.tec.cr
      PGADMIN_DEFAULT_PASSWORD: pass
    networks:
      - default
    ports:
      - 5050:80

#  mongoexpress:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    networks:
#      - default
#    environment:
#      ME_CONFIG_MONGODB_SERVER: dbmongo
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root

# ---------------------------------------------------

networks:
  default:
    driver: bridge

volumes:
  postgres-data:
  mongodb-data:
  