name: Coverage Testing, Build And Publish Image to Docker

on:
  push:
    branches: [ "main" ]

jobs:
    cov_and_publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.12'

            - name: Setup Compose
              run: docker compose up -d --build

            - name: Run tests
              run: |
                docker exec -t py01-viajesapp-webapp-1 /bin/bash -c "poetry run coverage run -m pytest tests/testdb.py && poetry run coverage xml"

            - name: Copy XML
              run: |
                docker cp py01-viajesapp-webapp-1:app/coverage.xml ./

            - name: Parse coverage
              id: coverage
              run: |
                COVERAGE=$(python -c "import xml.etree.ElementTree as ET; print(ET.parse('coverage.xml').getroot().attrib['line-rate'])")
                echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

            - name: Verify coverage
              if: steps.coverage.outputs.coverage < 0.85
              run: exit 1

            - name: build-image
              if: steps.coverage.outputs.coverage >= 0.85
              run: docker build . -t studentpublishing7/travels_proyect_app:latest

            - name: Push Image to Docker Hub
              if: steps.coverage.outputs.coverage >= 0.85
              run: |
                docker login -u studentpublishing7 -p ${{ secrets.DOCKER_HUB_TOKEN }}
                docker push studentpublishing7/travels_proyect_app:latest
